apiVersion: v1
kind: Secret # Indicates what kind of kubernetes component we are dealing with
metadata:
  name: ab-mongo-secret    # We will refer this name in deployment wherever this secret is used to fetch details
type: Opaque # This is a type of secret
data:
  ab-mongo-root-username: YW5pbGJoYXR0
  # This field name "ab-mongo-root-username" should exactly match with "key" of env variable MONGO_INITDB_ROOT_USERNAME in deployment yaml
  ab-mongo-root-password: cGFzc3dvcmQxMjM=
  # This field name "ab-mongo-root-password" should exactly match with "key" of env variable MONGO_INITDB_ROOT_PASSWORD in deployment yaml